src/home/urls.py
from django.conf.urls import include,url
from home.views import PaginaPrincipal, ShapePolyList, ShapePointList
from home.shapes import ShapePolyCargar, ShapePointCargar

urlpatterns = [
    url(r'^$', PaginaPrincipal.as_view(), name='inicio'),
	url(r'^home/shapes/poly/$', ShapePolyCargar.as_view(), name='shape_poligono_cargar'),
	url(r'^home/shapes/poly/cargar/$', ShapePolyCargar.upload_shape_polygon, name='upload_shape_polygon'),
	url(r'^home/shapes/poly/listar$', ShapePolyList.as_view(), name='shape_poligono_listar'),
	url(r'^home/shapes/point/$', ShapePointCargar.as_view(), name='shape_punto_cargar'),
	url(r'^home/shapes/point/cargar$', ShapePointCargar.upload_shape_point, name='upload_shape_point'),
	url(r'^home/shapes/point/listar$', ShapePointList.as_view(), name='shape_point_listar'),
]

src/sigrnnuble/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls',namespace="home")),
    url(r'^poly/', include('cpoly.urls')),
    url(r'^point/', include('cpoint.urls')),
    #url(r'^line/', include('cline.urls')),

]

src/templates/sig/shape_poligono_cargar.html
{% extends 'adminlte/base.html' %}
{% block title %}Cargar shape polígonos al sistema{% endblock %}

{% load i18n %}
{% load bootstrap3 %}

{% block css %}
    {% load static %}
    <style>
        .change-password {
            margin-top: 20px;
            margin-bottom: 20px;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="ibox float-e-margins">
                <div class="panel-body ibox float-e-margins panel panel-default">
                    <div class="tab-content">
                        <div class="col-lg-12" id="menu-limitesprediales">
                            <form class="limitepredial" action="{% url 'home:upload_shape_polygon' %}"
                                  enctype="multipart/form-data" method="POST" role="form" id="ShapePoly">

                                <div class="col-lg-12">
                                    <div style="background:#c62828;border-radius: 3px;">
                                        {% if errMsg %}
                                            <h4 style="color: white;text-align:justify; padding: 20px;"><b><i>{{ errMsg }}</i></b></h4>
                                        {% endif %}
                                        </div>
                                    <h1 style="text-transform: uppercase; font-weight: bold;">Cargar shape de polígonos al sistema</h1>
                                    <hr>
                                    <h3 style="text-transform: uppercase; text-align:center;">PUNTOS A CONSIDERAR ANTES DE COMENZAR</h3>
                                    <div style="background:#235e7f;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px;margin-bottom: 5px;">
                                    <h4 style="text-align: justify;color:white; font-size: 15px">Cada vez que cargue un nuevo shape al sistema se
                                        borrán
                                        irreversiblemente los datos anteriores de la base de datos.</h4>
                                    </div>
                                <div style="background:#235e7f;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px;margin-bottom: 5px;">
                                    <h4 style="text-align: justify;color:white; font-size: 15px">Si por algún motivo requiere cargar un shape anterior
                                        del
                                        cual sus datos fueron borrados, visite la sección "Listar Shapes", allí puede extraer
                                        un shape cargado anteriormente filtrando la busqueda por fecha.</h4>
                                    </div>
                                <div style="background:#235e7f;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px;margin-bottom: 5px;">
                                    <h4 style="text-align: justify;color:white; font-size: 15px">Verifique que el archivo.zip contenga como mínimo los 4
                                        archivos
                                        necesarios para la carga correcta del shape (.shp, .shx, .dbf, .prj).</h4>
                                    </div>
                                    <div style="background:#235e7f;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px;margin-bottom: 5px;">
                                    <h4 style="text-align: justify;color:white; font-size: 15px">La tabla de referencia, le muestra a usted los datos
                                        que
                                        debe
                                        contener el shape a subir. No intente subir archivos con otra estructura.</h4>
                                    </div>
                                    <div style="background:#235e7f;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px">
                                    <h4 style="text-align: justify;color:white; font-size: 15px">En las tablas de referencia se omite el atributo "geom",
                                        esto porque es obligatorio en un archivo .shp válido, entonces se asume su presencia.</h4>
                                    </div>
                                    <br><br>
                                    <div class="col-lg-12" style="padding-top: 5px;padding-bottom: 20px;padding-right:40px;padding-left: 40px;border-radius: 5px;box-shadow: 0px 0.5px 8px gray;">
                                    <h3 style="text-transform: uppercase; text-align: center;">Cargar shape de polígonos</h3>
                                    <h4 style="text-align: justify;">Porfavor, busque el archivo .zip en el ordenador, seleccione el archivo y presione en "CARGAR" para cargar el shape y sus datos en el sistema.</h4>
                                    <br>
                                    <div class="col-lg-3">
                                        {% bootstrap_field form.archivo_zip_shape %}
                                    </div>
                                    <div class="col-lg-9">
                                        <br>
                                        <button style="text-justify: inter-word;" type="submit" value="Subir" id="ShapePoly"
                                                class="btn btn-primary glyphicon glyphicon-cloud-upload  fa-pull-right">
                                            CARGAR
                                        </button>
                                    </div>
                                                                        <div class="col-lg-12">
                                         <div style="background:#00796b;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px">
                                    <h4 style="text-align: justify;color: white; text-align: justify; font-size: 16px">Recuerde que el shape debe contar con la misma estructura que se muestra en la tabla de referencia al final del formulario, de lo contrario, no podrá cargar el shape en el sistema.</h4>
                                    </div>
                                    </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <br>
                                    <h3 style="color: #263238;text-transform: uppercase; text-align: center;">Tabla de referencia de la estructura del shape</h3>
                                    <br>
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-striped">
                                            
                                            <tr>
                                                <th>id_poly</th>
                                                <th>snaspe</th>
                                                <th>tipo</th>
                                                <th>superficie</th>
                                                <th>descripcio</th>
                                                <th>nom_regi</th>
                                                <th>nom_prov</th>
                                                <th>nom_comuna</th>
                                                <th>horario_in</th>
                                                <th>horario_ve</th>
                                                <th>shape_leng</th>
                                                <th>shape_area</th>
                                            </tr>
                                            <tr>
                                                <td>DECIMAL</td>
                                                <td>DECIMAL</td>
                                                <td>DECIMAL</td>
                                                <td>DECIMAL</td>
                                                <td>TEXTO</td>
                                                <td>TEXTO</td>
                                                <td>TEXTO</td>
                                                <td>TEXTO</td>
                                                <td>TEXTO</td>
                                                <td>TEXTO</td>
                                                <td>DECIMAL</td>
                                                <td>DECIMAL</td>
                                            </tr>
                                        </table>
                                    </div>
                                    <div class="table-responsive">
                                        <br><br>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/templates/sig/shape_poligono_listar.html
{% extends 'adminlte/base.html' %}
{% block head_title %} LimitesPrediales-Listar {% endblock %}
{% load render_table from django_tables2 %}

{% block content %}

    <div class="">

        <!-- Busqueda -->

        <div class="row filter-header">
            <div class="col-md-4">
                <form id="search-form" action="" method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" value="{{ q }}" placeholder="Buscar por: Nombre o Rol" autofocus/>
                        <span class="input-group-addon" onclick="document.getElementById('search-form').submit()">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </form>
            </div>
        </div>

        <!-- Fin Búsqueda -->

        <div class="row">
            <div class="col-md-12">
                <div class="ibox float-e-margins panel panel-default">
                    <div class="panel-body">
                        <h3>Shape polígonos</h3>
                    </div>

                    <div class="table-container table-responsive">
                        <div class="panel-body">

                            {% render_table table %}

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/templates/sig/shape_punto_cargar.html
{% extends 'adminlte/base.html' %}
{% block title %}Cargar shape de puntos al sistema{% endblock %}

{% load i18n %}
{% load bootstrap3 %}

{% block css %}
    {% load static %}
    <style>
        .change-password {
            margin-top: 20px;
            margin-bottom: 20px;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="ibox float-e-margins">
                <div class="panel-body ibox float-e-margins panel panel-default">
                    <div class="tab-content">
                        <div class="col-lg-12" id="menu-limitesprediales">
                            <form class="limitepredial" action="{% url 'home:upload_shape_point' %}"
                                  enctype="multipart/form-data" method="POST" role="form" id="ShapePoint">

                                <div class="col-lg-12">
                                    <div style="background:#c62828;border-radius: 3px;">
                                        {% if errMsg %}
                                            <h4 style="color: white;text-align:justify; padding: 20px;"><b><i>{{ errMsg }}</i></b></h4>
                                        {% endif %}
                                        </div>
                                    <h1 style="text-transform: uppercase; font-weight: bold;">Cargar shape de puntos al sistema</h1>
                                    <hr>
                                    <h3 style="text-transforwm: uppercase; text-align:center;">PUNTOS A CONSIDERAR ANTES DE COMENZAR</h3>
                                    <div style="background:#235e7f;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px;margin-bottom: 5px;">
                                    <h4 style="text-align: justify;color:white; font-size: 15px">Cada vez que cargue un nuevo shape al sistema se
                                        borrán
                                        irreversiblemente los datos anteriores de la base de datos.</h4>
                                    </div>
                                <div style="background:#235e7f;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px;margin-bottom: 5px;">
                                    <h4 style="text-align: justify;color:white; font-size: 15px">Si por algún motivo requiere cargar un shape anterior
                                        del
                                        cual sus datos fueron borrados, visite la sección "Listar Shapes", allí puede extraer
                                        un shape cargado anteriormente filtrando la busqueda por fecha.</h4>
                                    </div>
                                <div style="background:#235e7f;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px;margin-bottom: 5px;">
                                    <h4 style="text-align: justify;color:white; font-size: 15px">Verifique que el archivo.zip contenga como mínimo los 4
                                        archivos
                                        necesarios para la carga correcta del shape (.shp, .shx, .dbf, .prj).</h4>
                                    </div>
                                    <div style="background:#235e7f;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px;margin-bottom: 5px;">
                                    <h4 style="text-align: justify;color:white; font-size: 15px">La tabla de referencia, le muestra a usted los datos
                                        que
                                        debe
                                        contener el shape a subir. No intente subir archivos con otra estructura.</h4>
                                    </div>
                                    <div style="background:#235e7f;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px">
                                    <h4 style="text-align: justify;color:white; font-size: 15px">En las tablas de referencia se omite el atributo "geom",
                                        esto porque es obligatorio en un archivo .shp válido, entonces se asume su presencia.</h4>
                                    </div>
                                    <br><br>
                                    <div class="col-lg-12" style="padding-top: 5px;padding-bottom: 20px;padding-right:40px;padding-left: 40px;border-radius: 5px;box-shadow: 0px 0.5px 8px gray;">
                                    <h3 style="text-transform: uppercase; text-align: center;">Cargar shape de puntos</h3>
                                    <h4 style="text-align: justify;">Porfavor, busque el archivo .zip en el ordenador, seleccione el archivo y presione en "CARGAR" para cargar el shape y sus datos en el sistema.</h4>
                                    <br>
                                    <div class="col-lg-3">
                                        {% bootstrap_field form.archivo_zip_shape %}
                                    </div>
                                    <div class="col-lg-9">
                                        <br>
                                        <button style="text-justify: inter-word;" type="submit" value="Subir" id="ShapePoly"
                                                class="btn btn-primary glyphicon glyphicon-cloud-upload  fa-pull-right">
                                            CARGAR
                                        </button>
                                    </div>
                                                                        <div class="col-lg-12">
                                         <div style="background:#00796b;border-radius: 3px;padding-top: 3px;padding-bottom: 3px;  padding-left: 15px; padding-right: 15px">
                                    <h4 style="text-align: justify;color: white; text-align: justify; font-size: 16px">Recuerde que el shape debe contar con la misma estructura que se muestra en la tabla de referencia al final del formulario, de lo contrario, no podrá cargar el shape en el sistema.</h4>
                                    </div>
                                    </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <br>
                                    <h3 style="color: #263238;text-transform: uppercase; text-align: center;">Tabla de referencia de la estructura del shape</h3>
                                    <br>
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-striped">
                                            <tr>
                                                <th>id_point</th>
                                                <th>snaspe</th>
                                                <th>tipo</th>
                                                <th>superficie</th>
                                                <th>descripcio</th>
                                                <th>nom_regi</th>
                                                <th>nom_comuna</th>
                                                <th>nom_prov</th>
                                                <th>shape_leng</th>
                                                <th>shape_area</th>
                                                <th>horario_in</th>
                                                <th>horario_ve</th>
                                            </tr>
                                            <tr>
                                                <td>DECIMAL</td>
                                                <td>DECIMAL</td>
                                                <td>TEXTO</td>
                                                <td>DECIMAL</td>
                                                <td>TEXTO</td>
                                                <td>TEXTO</td>
                                                <td>TEXTO</td>
                                                <td>TEXTO</td>
                                                <td>DECIMAL</td>
                                                <td>DECIMAL</td>
                                                <td>TEXTO</td>
                                                <td>TEXTO</td>
                                            </tr>
                                        </table>
                                    </div>
                                    <div class="table-responsive">
                                        <br><br>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/templates/sig/shape_punto_listar.html
{% extends 'adminlte/base.html' %}
{% block head_title %} LimitesPrediales-Listar {% endblock %}
{% load render_table from django_tables2 %}

{% block content %}

    <div class="">

        <!-- Busqueda -->

        <div class="row filter-header">
            <div class="col-md-4">
                <form id="search-form" action="" method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" value="{{ q }}" placeholder="Buscar por: Nombre o Rol" autofocus/>
                        <span class="input-group-addon" onclick="document.getElementById('search-form').submit()">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </form>
            </div>
        </div>


        <!-- Fin Búsqueda -->

        <div class="row">
            <div class="col-md-12">
                <div class="ibox float-e-margins panel panel-default">
                    <div class="panel-body">
                        <h3>Shape puntos</h3>
                    </div>

                    <div class="table-container table-responsive">
                        <div class="panel-body">

                            {% render_table table %}

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}